### PR TITLE
722 wait no longer needed in cypress tests

### LINKED ISSUE #722: Wait no longer needed in cypress tests
We have a number of flaky cypress tests, for which we use the cy wait function.

However, it seems that after #716 added retries, this should not be necessary anymore.

We should remove the calls to cy.wait where possible.

### PR DESCRIPTION
**Pull request by Bdegraaf1234**
Description: Remove unneeded wait commands from cypress tests

Fixes #722 

#### Checklist:
- [ ] The [Main workflow](https://github.com/RADAR-base/ManagementPortal/actions/workflows/main.yml) has succeeded
- [ ] The [Gatling tests](https://github.com/RADAR-base/ManagementPortal#other-tests) have passed
- [ ] I have logged into the portal running locally with default admin credentials
- [ ] I have updated the README files if this change requires documentation update
- [ ] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by Bdegraaf1234** [comment]
Unfortunately, it seems that the need for wait is not removed.

One way to achieve non-arbitrary wait times would be to add guards by intercepting the xhr requests.

```
cy.intercept("GET", "/api/projects/radar/subjects?size=20&sort=login,desc").as("sort")
cy.get('jhi-subjects #order-by-desc').click();
cy.wait("@sort");
```
However, this seems like quite a bit more work and the wait times are not that long. I have also failed to find the logic in where the wait commands are needed.

I was able to remove three out of 4 without causing problems here.

**Comment by blootsvoets** [comment]
Failed tests with a lot of try / retry probably will still need the original wait. Once fixed, can this be merged or is it still WIP?

**Comment by Bdegraaf1234** [comment]
Turned out to be pretty small changes, I left the alternative wait strategy in with a comment. ready for review

**Review by blootsvoets — APPROVED** [review]
LGTM

**Pull request merged**
