### PR TITLE
Release 0.8.2

### PR DESCRIPTION
**Pull request by mpgxvii**
Description: 
- Change response of activationReset from String to Object with HttpStatus.NO_CONTENT
- Updates radar-auth: Continue pulling public key endpoints even if one fails 
- Updates README
- Updates GA from `Mp2.0-rc branch`

### CODE REVIEW

**Review by yatharthranjan — COMMENTED** [review]
There are integration tests failing. Is that expected?

**Comment by mpgxvii** [comment]
> There are integration tests failing. Is that expected?

The main, pre-release, and release workflows are now successful, but there seems to be some issues with the snyk ones.

**Review by yatharthranjan — DISMISSED** [review]
LGTM, but i think it requires code review from @blootsvoets or @nivemaham.

**Review by nivemaham — DISMISSED** [review]
LGTM

**Review by nivemaham — APPROVED** [review]
LGTM

**Pull request merged**
