### PR TITLE
Fix/login redirects

### PR DESCRIPTION
**Pull request by Bdegraaf1234**
Login redirects were not set correctly in #879, additionally the antmatchers were not set in all required locations.

This should resolve the issue and add some other small improvements.

### CODE REVIEW

**Comment by Bdegraaf1234** [comment]
@mpgxvii please correct me if I am wrong but for me therequests to `/api/redirect/login/` returned 401 at some point. I am double checking this as we speak though

**Comment by mpgxvii** [comment]
> @mpgxvii please correct me if I am wrong but for me therequests to `/api/redirect/login/` returned 401 at some point. I am double checking this as we speak though

The previous security config were working for me. It was just the front end url that didn't work. Let me double check as well.

**Comment by Bdegraaf1234** [comment]
I think you were right pauline, apologies. I will remove the lines, can you review the this PR?

**Review by mpgxvii — APPROVED** [review]
LGTM, sorry for the confusion. Thanks so much!

**Pull request merged**
