### PR TITLE
Expost secret with meta token

### PR DESCRIPTION
**Pull request by nivemaham**
- exposes `client-secret` with Meta-token

### CODE REVIEW

**Comment by nivemaham** [comment]
@blootsvoets @dennyverbeeck 
I realized the `client-secret` I get from ClientCredential is encoded by `BCryptPasswordEncoder`. Do you guys know how this can be decoded? 
@blootsvoets Do we prefer to transfer encoded secret over the wire, and decode it on client side?

In both cases, I could not find a way to decode this. The PasswordEncoder provides `encode` and `matches` interfaces. But I do not find anything that can decode.

**Comment by blootsvoets** [comment]
If it's documented then I think it's okay. Then clients can check if they know the password, and if they don't, they can notify clients that they don't know the password. This would work well with a demo password: the client can test whether the demo password is correct, and if it is, the server works as a demo server. Otherwise, the server is off limits. Then it's up to admins to set the correct demo password.

**Comment by dennyverbeeck** [comment]
Aha, yes that is true. BCrypt is a hash function, so it's one-way, you can not reverse it.

I was looking around a bit again, apparently it should be possible to configure the client secret as an empty string, which should allow that client to use the token endpoint without a client secret ([source](https://stackoverflow.com/a/48545161)). If this is the case i think this is the way to go for our public clients. What do you think @blootsvoets ?

If for some reason we can not set an empty secret, we can also configure the same secret for all public clients, e.g. `radar_client`.

**Comment by dennyverbeeck** [comment]
So, i just confirmed we can use the public OAuth clients without a client secret. I left the secret field empty in the `oauth_client_details.csv` file. Then, after obtaining a metatoken and parsing the refresh token out of the endpoint response, i could use the refresh token as being the pRMT app without supplying a client secret, as seen by the below `curl` call and response:

```
curl -XPOST http://pRMT@localhost:8080/oauth/token -F "grant_type=refresh_token" -F "refresh_token=$rtoken"
{
  "access_token" : "eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NiJ9.eyJzdWIiOiJzdWItMSIsInNvdXJjZXMiOlsiMDNkMjhlNWMtZTAwNS00NmQ0LWE5YjMtMjc5YzI3ZmJiYzgzIl0sInVzZXJfbmFtZSI6InN1Yi0xIiwicm9sZXMiOlsicmFkYXI6Uk9MRV9QQVJUSUNJUEFOVCJdLCJpc3MiOiJNYW5hZ2VtZW50UG9ydGFsIiwiYXV0aG9yaXRpZXMiOlsiUk9MRV9QQVJUSUNJUEFOVCJdLCJjbGllbnRfaWQiOiJwUk1UIiwiYXVkIjpbInJlc19nYXRld2F5IiwicmVzX01hbmFnZW1lbnRQb3J0YWwiXSwiZ3JhbnRfdHlwZSI6ImF1dGhvcml6YXRpb25fY29kZSIsInNjb3BlIjpbIk1FQVNVUkVNRU5ULkNSRUFURSIsIlNVQkpFQ1QuVVBEQVRFIiwiU1VCSkVDVC5SRUFEIiwiUFJPSkVDVC5SRUFEIiwiU09VUkNFVFlQRS5SRUFEIiwiU09VUkNFLlJFQUQiLCJTT1VSQ0VEQVRBLlJFQUQiLCJVU0VSLlJFQUQiLCJST0xFLlJFQUQiXSwiZXhwIjoxNTM1MDg2OTg3LCJpYXQiOjE1MzUwNDM3ODcsImp0aSI6IjdjNTI3MDQ4LTM3NzUtNDk1MS1iN2IzLTliNjhkMTZhMTJjOSJ9.MEUCIFKeuttWxs-TXDAyImKSWR2K5mIHRuW9jmAXrZaZtFA2AiEA4W5MCCoOIGJVXrK1k5rnEHwS_XJasnSCDj4Wz0jyEO4",
  "token_type" : "bearer",
  "refresh_token" : "eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NiJ9.eyJzdWIiOiJzdWItMSIsInNvdXJjZXMiOlsiMDNkMjhlNWMtZTAwNS00NmQ0LWE5YjMtMjc5YzI3ZmJiYzgzIl0sInVzZXJfbmFtZSI6InN1Yi0xIiwicm9sZXMiOlsicmFkYXI6Uk9MRV9QQVJUSUNJUEFOVCJdLCJpc3MiOiJNYW5hZ2VtZW50UG9ydGFsIiwiYXV0aG9yaXRpZXMiOlsiUk9MRV9QQVJUSUNJUEFOVCJdLCJjbGllbnRfaWQiOiJwUk1UIiwiYXVkIjpbInJlc19nYXRld2F5IiwicmVzX01hbmFnZW1lbnRQb3J0YWwiXSwiZ3JhbnRfdHlwZSI6ImF1dGhvcml6YXRpb25fY29kZSIsInNjb3BlIjpbIk1FQVNVUkVNRU5ULkNSRUFURSIsIlNVQkpFQ1QuVVBEQVRFIiwiU1VCSkVDVC5SRUFEIiwiUFJPSkVDVC5SRUFEIiwiU09VUkNFVFlQRS5SRUFEIiwiU09VUkNFLlJFQUQiLCJTT1VSQ0VEQVRBLlJFQUQiLCJVU0VSLlJFQUQiLCJST0xFLlJFQUQiXSwiYXRpIjoiN2M1MjcwNDgtMzc3NS00OTUxLWI3YjMtOWI2OGQxNmExMmM5IiwiZXhwIjoxNTQyOTkyNTg3LCJpYXQiOjE1MzUwNDM3ODcsImp0aSI6ImI5Yjc5YWRhLWIzMDMtNDk1MC05OWE2LTUzYmU1NDkyNjRmNSJ9.MEYCIQCT34GEDz77Z1CUVFRJXU4xBmJwNQYcXRCGW0xdWaoFDQIhAJwzFUMjUeKST5ZwCCiY2Rr0UlMmCnqgs0ZUV_c5tBSc",
  "expires_in" : 43199,
  "scope" : "MEASUREMENT.CREATE SUBJECT.UPDATE SUBJECT.READ PROJECT.READ SOURCETYPE.READ SOURCE.READ SOURCEDATA.READ USER.READ ROLE.READ",
  "sub" : "sub-1",
  "sources" : [ "03d28e5c-e005-46d4-a9b3-279c27fbbc83" ],
  "grant_type" : "authorization_code",
  "roles" : [ "radar:ROLE_PARTICIPANT" ],
  "iss" : "ManagementPortal",
  "iat" : 1535043787,
  "jti" : "7c527048-3775-4951-b7b3-9b68d16a12c9"
}
```

Therefore i think we should go with this approach, as it adheres to the OAuth spec recommendation of not using a client secret at all with public clients.

I'll open a new PR to take out again the client secret from the `TokenDTO` class. I think the other changes in this PR are fine. Storing the client id with the metatoken can be useful as an extra security measure, if you need to know the token URL AND the client id this further increases the difficulty to brute-force the metatoken endpoint.

**Comment by blootsvoets** [comment]
@dennyverbeeck sounds fine. It requires a few client changes:
- the defaults in this repo and in RADAR-docker should have empty secrets for clients with `authorized_code` and without `client_credentials` or `password`.
- the defaults for the RADAR clients should also have an empty password.

**Pull request merged**
